server:
  port: 8082
dubbo:
  registry:
    address: zookeeper://192.168.40.130:2181
  application:
    name: qg-user-consumer
spring:
  redis:
    host: 192.168.40.130
    port: 6379
    password: 123456
    lettuce:
      pool:
        max-active: 8   #连接池最大连接数（使用负值表示没有限制）
        min-idle: 0     # 连接池中的最小空闲连接
        max-idle: 8     # 连接池中的最大空闲连接
        max-wait: -1    # 连接池最大阻塞等待时间（使用负值表示没有限制）
